name: Auto Update Portfolio Cards

on:
  push:
    paths:
      - "source/pages/**/*.html"

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate cards
        run: python generate_cards.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add index.html

          if ! git diff --cached --quiet; then
            git commit -m "Auto update portfolio cards"
            git push
          else
            echo "No changes to commit"
          fi
